# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest scipy coverage
        pip install https://github.com/pypr/compyle/zipball/master
    - name: PEP8 Action
      # You may pin to the exact commit or the version.
      # uses: quentinguidee/pep8-action@acad1c4f4dec1dff6424e25d3b599c60c422281e
      uses: quentinguidee/pep8-action@v1
    - name: Test with pytest
      run: |
        coverage report -m
