name: Tests

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
  
  

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.9]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - name: Install dependencies on Linux
        run: |
          python -m pip install --upgrade pip
          conda install -c conda-forge pocl pyopencl pytest scipy pyyaml
          python -c 'import pyopencl as cl'
          pip install https://github.com/pypr/compyle/zipball/master
      - name: PEP8 Action
        uses: quentinguidee/pep8-action@v1
      - name: Run tests
        run: |
          pytest
